baseURL: https://santijes.github.io
languageCode: en-us
title: Portfolio
theme: "lekh"

params:
  Name: Santiago Jiménez Escorsa
  About: >-
    We're not here because we're free. We're here because we're __not__ free.
    There's no escaping reason. No denying purpose. Because as we both know
    without purpose, we would not exist.<br/> Read more
    [here](https://matrix.fandom.com/wiki/Agent_Smith)
  Email: yosantije@gmail.com
  Resume: ''
  PostLimit: 4
  GoatCounterCode: ''
  profiles:
    - name: GitHub
      url: 'https://github.com/SantiJEs'
    - name: LinkedIn
      url: 'https://LinkedIn.es'
    - name: Twitter
      url: 'https://twitter.com'
