baseURL: https://santijes.github.io
languageCode: en-us
title: My New Hugo Site
theme: "lekh"

params:
  Name: Agent Smith
  About: >-
    We're not here because we're free. We're here because we're __not__ free.
    There's no escaping reason. No denying purpose. Because as we both know
    without purpose, we would not exist.<br/> Read more
    [here](https://matrix.fandom.com/wiki/Agent_Smith)
  Email: agentsmith@thematrix.com
  Resume: ''
  PostLimit: 4
  GoatCounterCode: ''
  profiles:
    - name: GitHub
      url: 'https://github.com/ba11b0y'
    - name: Twitter
      url: 'https://twitter.com/ba11b0y'
    - name: Goodreads
      url: 'https://www.goodreads.com/user/show/91520565-rahul-tiwari'
    - name: LinkedIn
      url: ''
